### PR TITLE
[AIRFLOW-XXXX] Use Github Actions for CI

### PR DESCRIPTION
**Pull request by turbaszek**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by nuclearpinguin** [comment]
@potiuk can you take a look at k8s builds? Both fails due to:
```
Step 6/6 : ENTRYPOINT ["/bootstrap.sh"]
1483
 ---> Running in e8cf5350812f
1484
Removing intermediate container e8cf5350812f
1485
 ---> f319ceefae12
1486
Successfully built f319ceefae12
1487
Successfully tagged airflow:latest
1488
Error: failed to load image: exit status 1
1489
##[error]Process completed with exit code 1.
```

**Comment by potiuk** [comment]
I do not know the reason yet. But maybe try to run the "load" part with sudo. What happens it that we are executing 'kind load'
```
kind load docker-image "${IMAGE}:${TAG}"
```
This should take the image from docker registry and load it to the "internal" registry of kind (kubernetes in docker) so that it can be used to run PODs. It fails with mysterious error 1 - which might be some kind of permission for that machine  or misconfiguration of kind ...

**Comment by nuclearpinguin** [comment]
```
Successfully built 4737549972ec
1480
Successfully tagged airflow:latest
1481
Kubernetes master is running at https://docker:19090
1482
KubeDNS is running at https://docker:19090/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
1483

1484
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
1485
Image: airflow:latest
1486
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
1487
time="13:41:37" level=debug msg="Running: /usr/bin/docker [docker image inspect -f {{ .Id }} airflow:latest]"
1488
time="13:41:37" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}}]"
1489
time="13:41:37" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}} --filter label=io.k8s.sigs.kind.cluster=kind]"
1490
time="13:41:37" level=debug msg="Running: /usr/bin/docker [docker inspect -f {{index .Config.Labels \"io.k8s.sigs.kind.role\"}} kind-worker]"
1491
time="13:41:37" level=debug msg="Running: /usr/bin/docker [docker inspect -f {{index .Config.Labels \"io.k8s.sigs.kind.role\"}} kind-control-plane]"
1492
time="13:41:37" level=debug msg="Running: /usr/bin/docker [docker exec --privileged kind-worker crictl inspecti airflow:latest]"
1493
time="13:41:37" level=debug msg="Image: \"airflow:latest\" with ID \"sha256:4737549972ecb17fbe34d9164f52c57c2e5d96c3587b773bc6c92c7a915295aa\" not present on node \"kind-worker\""
1494
time="13:41:37" level=debug msg="Running: /usr/bin/docker [docker exec --privileged kind-control-plane crictl inspecti airflow:latest]"
1495
time="13:41:37" level=debug msg="Image: \"airflow:latest\" with ID \"sha256:4737549972ecb17fbe34d9164f52c57c2e5d96c3587b773bc6c92c7a915295aa\" not present on node \"kind-control-plane\""
1496
time="13:41:37" level=debug msg="Running: /usr/bin/docker [docker save -o /tmp/image-tar828391455/image.tar airflow:latest]"
1497
time="13:45:21" level=debug msg="Running: /usr/bin/docker [docker exec --privileged -i kind-control-plane ctr --namespace=k8s.io images import -]"
1498
time="13:45:21" level=debug msg="Running: /usr/bin/docker [docker exec --privileged -i kind-worker ctr --namespace=k8s.io images import -]"
1499
Error: failed to load image: exit status 1
1500
##[error]Process completed with exit code 1.
```

**Comment by nuclearpinguin** [comment]
```
Successfully built acdbd8b066e7
1487
Successfully tagged airflow:latest-21988
1488
REPOSITORY          TAG                   IMAGE ID            CREATED             SIZE
1489
airflow             latest-21988          acdbd8b066e7        1 second ago        3.24GB
1490
apache/airflow      master-python3.6-ci   c73034976597        4 hours ago         3.24GB
1491
kindest/node        v1.15.3               8ca0c8463ebe        3 months ago        1.45GB
1492
Kubernetes master is running at https://docker:19090
1493
KubeDNS is running at https://docker:19090/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
1494

1495
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
1496
sha256:acdbd8b066e7f730a98c749c0e1d2da938f3356e1de99f70fcd4d2b6f4ca720e
1497
time="21:30:39" level=debug msg="Running: /usr/bin/docker [docker image inspect -f {{ .Id }} airflow:latest-21988]"
1498
time="21:30:39" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}}]"
1499
time="21:30:39" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}} --filter label=io.k8s.sigs.kind.cluster=kind]"
1500
time="21:30:39" level=debug msg="Running: /usr/bin/docker [docker inspect -f {{index .Config.Labels \"io.k8s.sigs.kind.role\"}} kind-control-plane]"
1501
time="21:30:39" level=debug msg="Running: /usr/bin/docker [docker inspect -f {{index .Config.Labels \"io.k8s.sigs.kind.role\"}} kind-worker]"
1502
time="21:30:39" level=debug msg="Running: /usr/bin/docker [docker exec --privileged kind-control-plane crictl inspecti airflow:latest-21988]"
1503
time="21:30:40" level=debug msg="Image: \"airflow:latest-21988\" with ID \"sha256:acdbd8b066e7f730a98c749c0e1d2da938f3356e1de99f70fcd4d2b6f4ca720e\" not present on node \"kind-control-plane\""
1504
time="21:30:40" level=debug msg="Running: /usr/bin/docker [docker exec --privileged kind-worker crictl inspecti airflow:latest-21988]"
1505
time="21:30:40" level=debug msg="Image: \"airflow:latest-21988\" with ID \"sha256:acdbd8b066e7f730a98c749c0e1d2da938f3356e1de99f70fcd4d2b6f4ca720e\" not present on node \"kind-worker\""
1506
time="21:30:40" level=debug msg="Running: /usr/bin/docker [docker save -o /tmp/image-tar444364156/image.tar airflow:latest-21988]"
1507
time="21:34:24" level=debug msg="Running: /usr/bin/docker [docker exec --privileged -i kind-worker ctr --namespace=k8s.io images import -]"
1508
time="21:34:24" level=debug msg="Running: /usr/bin/docker [docker exec --privileged -i kind-control-plane ctr --namespace=k8s.io images import -]"
```
I have no idea what can be wrong here. @potiuk @mik-laj

**Comment by nuclearpinguin** [comment]
I think I tracked down the reason:
```
ctr: unrecognized image format
##[error]Process completed with exit code 1.
```

**Comment by potiuk** [comment]
I think it's really a problem with kind ... I am getting to the point when I think we should switch to using mcirok8s instead of kind :(

**Comment by dimberman** [comment]
regarding the failing kubernetes tests I have a few questions:

1. Are we sure taht the test is being run in the same namespace as the worker or in the cluster? I'm seeing it is using the cluster-local name so that won't work from any other namespaces.
2. Have you tried testing these in a local KinD cluster?
3. Is there a method for us to exactly mimic the github CI environment around this?

**Comment by potiuk** [comment]
> regarding the failing kubernetes tests I have a few questions:
> 
> 1. Are we sure taht the test is being run in the same namespace as the worker or in the cluster? I'm seeing it is using the cluster-local name so that won't work from any other namespaces.
> 2. Have you tried testing these in a local KinD cluster?
> 3. Is there a method for us to exactly mimic the github CI environment around this?

1. Yes
2. Yes
3. Yes and no - we can run the test in the same way as in Travis/GitHub but the exact setup/environment of Host/Docker. Is something about DNS setup and auto-detection of the DNS configuration in CoreDNS. 

The test works perfectly locally and in Travis. It only does not work in GitHub Actions. I did not have time to take a close look but the problem is as follows. 
- when we enter ./breeze (docker-compose) environment we forward the docker socket to inside container
- kind uses that socket and instlalls itself in the host's docker. This makes it much easier to send the image to kind's cluster - because the base image is ready when we enter the container, so we can use kind load directly.
- when kind cluster is created it also sets up CoreDNS as part of the setup. Kind somehow auto-detects the DNS configuration - possibly due to the fact that we are doing it from 
- the CoreDNS setup seems to work fine for internal names (so postgres pod is reachable from the kubernetes executor pods) but with default kind setup, the external addresses (github.com used in git-sync version) are not properly resolved
- In TravisCI i had to update coredns configuration to add forwarding to Google's DNS: https://github.com/apache/airflow/blob/master/scripts/ci/in_container/kubernetes/setup_kind_cluster.sh#L93 to make it works. IT works nicely with this fix - for both internal Kubernetes addresses and external ones
- in Github Actions, the default config of CoreDNS is different and Tomek tried to convert DNS configuration to work with both internal and external addresses - but it did not work so far.

The setup and how to execute it locally is described here:

https://github.com/apache/airflow/blob/master/TESTING.rst#running-tests-with-kubernetes

**Comment by dimberman** [comment]
@potiuk maybe we should use the KinD github action? Maybe they're taking steps that we aren't? https://github.com/marketplace/actions/kind-kubernetes-in-docker-action

**Comment by dimberman** [comment]
(at the minimum the author of the action might be able to help us on proper KinD settings for github actions).

**Comment by potiuk** [comment]
Hey Daniel - it's an interesting idea. But I want to have something working without Travis/Github Action specific solutions. Seems that they are doing the same that we do. The difference is that we are starting kind cluster from within the docker. However it gave me an idea. I think we can have a small kind custom image and create the cluster in that separate image and then connect to it similarly to the other integrations - that might make our image smaller (and I planned to do the same for the minicluster and some other binaries we start now inside the image).

**Comment by dimberman** [comment]
@turbaszek maybe we could start by just pushing the linting steps to upstream? Start saving some time on our builds?

**Comment by potiuk** [comment]
Yeah. I think that is a great idea @dimberman @turbaszek -> why don't we gradually move jobs while we are fixing Kubernetes tests...

**Comment by turbaszek** [comment]
@potiuk @dimberman but should we ran static checks both on Travis and Github Actions? The success of static checks is prerequisite for running tests

**Comment by potiuk** [comment]
True. So maybe let's start with the regular/core tests /docs etc. ?

**Pull request closed without merging**
